import {
	Menu,
	App,
	Editor,
	MarkdownView,
	Modal,
	Notice,
	Plugin,
	PluginSettingTab,
	Setting,
} from "obsidian";

import * as fs from "fs";
import * as path from "path";
import { shell } from "electron";

function touchFile(filePath: string, defaultText: string): void {
	const names = filePath.split(path.sep);
	const folders = names.slice(0, -1),
		file = names[names.length - 1];
	// currentPath = vaultPath
	let currentPath = this.app.vault.adapter.getBasePath();
	folders.forEach((folder) => {
		currentPath = path.join(currentPath, folder);
		if (!fs.existsSync(currentPath)) {
			fs.mkdirSync(currentPath);
		}
	});
	currentPath = path.join(currentPath, file);
	if (!fs.existsSync(currentPath)) {
		fs.writeFileSync(currentPath, defaultText);
	}
	// open the application draw.io with currentPath
	shell.openPath(currentPath);
}

export default class ExamplePlugin extends Plugin {
	async onload() {
		this.registerEvent(
			this.app.workspace.on("editor-menu", (menu, editor, view) => {
				let match = editor.getValue().match(/!\[\[(.*)\]\]$/);
				if (match) {
					let s: string = match[1];
					menu.addItem((item) => {
						item.setTitle("Open (by default app) " + s).onClick(
							async () => {
								if (s.match(/.*\.svg$/)) {
									touchFile(
										s,
										`<?xml version="1.0" encoding="UTF-8"?>
									<!-- Do not edit this file with editors other than draw.io -->
									<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
									<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="1px" height="1px" viewBox="-0.5 -0.5 1 1" content="&lt;mxfile host=&quot;Electron&quot; modified=&quot;2024-04-05T18:41:30.781Z&quot; agent=&quot;Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/24.1.0 Chrome/120.0.6099.109 Electron/28.1.0 Safari/537.36&quot; etag=&quot;a89vDpJkTJhJ8p6eFdAD&quot; version=&quot;24.1.0&quot; type=&quot;device&quot;&gt;&#10;  &lt;diagram name=&quot;Page-1&quot; id=&quot;74iVes_II4ZU_MvOdqYY&quot;&gt;&#10;    &lt;mxGraphModel dx=&quot;1908&quot; dy=&quot;1348&quot; grid=&quot;1&quot; gridSize=&quot;10&quot; guides=&quot;1&quot; tooltips=&quot;1&quot; connect=&quot;1&quot; arrows=&quot;1&quot; fold=&quot;1&quot; page=&quot;1&quot; pageScale=&quot;1&quot; pageWidth=&quot;1169&quot; pageHeight=&quot;827&quot; math=&quot;0&quot; shadow=&quot;0&quot;&gt;&#10;      &lt;root&gt;&#10;        &lt;mxCell id=&quot;0&quot; /&gt;&#10;        &lt;mxCell id=&quot;1&quot; parent=&quot;0&quot; /&gt;&#10;      &lt;/root&gt;&#10;    &lt;/mxGraphModel&gt;&#10;  &lt;/diagram&gt;&#10;&lt;/mxfile&gt;&#10;"><defs/><g/></svg>`
									);
								} else {
									touchFile(s, "");
								}
							}
						);
					});
				}
			})
		);
	}
}
